"""9 migration

Revision ID: 1cbaf943b0b9
Revises: 323fcd119951
Create Date: 2024-04-08 15:38:14.377068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbaf943b0b9'
down_revision: Union[str, None] = '323fcd119951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventparticipants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_rewiew', sa.Text(), nullable=True),
    sa.Column('event_rating', sa.Integer(), nullable=False),
    sa.Column('organizer_comment', sa.Text(), nullable=True),
    sa.CheckConstraint('event_rating BETWEEN 1 AND 5', name='check_event_rating'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventparticipants')
    # ### end Alembic commands ###
