"""17 migration

Revision ID: 2241026d1505
Revises: f37e37f047a9
Create Date: 2024-04-21 19:52:30.368198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2241026d1505'
down_revision: Union[str, None] = 'f37e37f047a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('isOnlyStudent', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'isOnlyStudent')
    # ### end Alembic commands ###
