"""14 migration

Revision ID: 2dcbe0eec25c
Revises: 5d87f00c5faf
Create Date: 2024-04-10 01:13:02.621823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcbe0eec25c'
down_revision: Union[str, None] = '5d87f00c5faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_organizations', sa.Column('avatar_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_organizations', 'avatar_file_name')
    # ### end Alembic commands ###
