"""11 migration

Revision ID: 2f44479dc911
Revises: debca78bb349
Create Date: 2024-04-09 14:20:34.405286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f44479dc911'
down_revision: Union[str, None] = 'debca78bb349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stud_org_name', sa.String(length=100), nullable=False),
    sa.Column('stud_org_description', sa.Text(), nullable=False),
    sa.Column('vk_link', sa.String(), nullable=True),
    sa.Column('telegram_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_organizer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('student_organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['student_organization_id'], ['student_organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.drop_table('student_organizatons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_organizatons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stud_org_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stud_org_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vk_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telegram_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='student_organizatons_pkey')
    )
    op.drop_table('event_organizer')
    op.drop_table('student_organizations')
    # ### end Alembic commands ###
