"""17 migration

Revision ID: 3cc4490d764e
Revises: f37e37f047a9
Create Date: 2024-04-11 22:58:12.192933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc4490d764e'
down_revision: Union[str, None] = 'f37e37f047a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('isModerated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'isModerated')
    # ### end Alembic commands ###
