"""13 migration

Revision ID: 5d87f00c5faf
Revises: 87fe3f7b6795
Create Date: 2024-04-09 23:15:17.558915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d87f00c5faf'
down_revision: Union[str, None] = '87fe3f7b6795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_participants', 'event_rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_participants', 'event_rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
