"""19 migration

Revision ID: 70388b5f6a8e
Revises: 108b431b3a18
Create Date: 2024-04-22 00:54:35.345870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70388b5f6a8e'
down_revision: Union[str, None] = '108b431b3a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_organizers_student_organization_id_fkey', 'event_organizers', type_='foreignkey')
    op.drop_constraint('event_organizers_event_id_fkey', 'event_organizers', type_='foreignkey')
    op.drop_constraint('event_organizers_user_id_fkey', 'event_organizers', type_='foreignkey')
    op.create_foreign_key(None, 'event_organizers', 'student_organizations', ['student_organization_id'], ['id'])
    op.create_foreign_key(None, 'event_organizers', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'event_organizers', 'users', ['user_id'], ['id'])
    op.drop_constraint('event_participants_event_id_fkey', 'event_participants', type_='foreignkey')
    op.drop_constraint('event_participants_user_id_fkey', 'event_participants', type_='foreignkey')
    op.create_foreign_key(None, 'event_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'event_participants', 'events', ['event_id'], ['id'])
    op.add_column('users', sa.Column('isVerified', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isVerified')
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.create_foreign_key('event_participants_user_id_fkey', 'event_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('event_participants_event_id_fkey', 'event_participants', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'event_organizers', type_='foreignkey')
    op.drop_constraint(None, 'event_organizers', type_='foreignkey')
    op.drop_constraint(None, 'event_organizers', type_='foreignkey')
    op.create_foreign_key('event_organizers_user_id_fkey', 'event_organizers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('event_organizers_event_id_fkey', 'event_organizers', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('event_organizers_student_organization_id_fkey', 'event_organizers', 'student_organizations', ['student_organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
