"""12 migration

Revision ID: 87fe3f7b6795
Revises: 2f44479dc911
Create Date: 2024-04-09 14:42:28.440695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fe3f7b6795'
down_revision: Union[str, None] = '2f44479dc911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_organization_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_organizers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('student_organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['student_organization_id'], ['student_organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('student_organization_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_organization_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['student_organization_roles.id'], ),
    sa.ForeignKeyConstraint(['student_organization_id'], ['student_organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'student_organization_id')
    )
    op.drop_table('event_organizer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_organizer',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_organizer_event_id_fkey'),
    sa.ForeignKeyConstraint(['student_organization_id'], ['student_organizations.id'], name='event_organizer_student_organization_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='event_organizer_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name='event_organizer_pkey')
    )
    op.drop_table('student_organization_members')
    op.drop_table('event_organizers')
    op.drop_table('student_organization_roles')
    # ### end Alembic commands ###
