"""10 migration

Revision ID: debca78bb349
Revises: 1cbaf943b0b9
Create Date: 2024-04-09 14:18:20.559684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debca78bb349'
down_revision: Union[str, None] = '1cbaf943b0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_organizatons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stud_org_name', sa.String(length=100), nullable=False),
    sa.Column('stud_org_description', sa.Text(), nullable=False),
    sa.Column('vk_link', sa.String(), nullable=True),
    sa.Column('telegram_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_rewiew', sa.Text(), nullable=True),
    sa.Column('event_rating', sa.Integer(), nullable=False),
    sa.Column('organizer_comment', sa.Text(), nullable=True),
    sa.CheckConstraint('event_rating BETWEEN 1 AND 5', name='check_event_rating'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('eventparticipants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventparticipants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_rewiew', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizer_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('event_rating >= 1 AND event_rating <= 5', name='check_event_rating'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='eventparticipants_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='eventparticipants_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='eventparticipants_pkey')
    )
    op.drop_table('event_participants')
    op.drop_table('student_organizatons')
    # ### end Alembic commands ###
