"""16 migration

Revision ID: f37e37f047a9
Revises: 9c6ac471925f
Create Date: 2024-04-10 02:48:01.344152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37e37f047a9'
down_revision: Union[str, None] = '9c6ac471925f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_file_name')
    # ### end Alembic commands ###
