"""6 migration

Revision ID: 8e34833e58a9
Revises: 0f685f151fb7
Create Date: 2024-04-07 16:54:26.109036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e34833e58a9'
down_revision: Union[str, None] = '0f685f151fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('starting_time', sa.DateTime(), nullable=False),
    sa.Column('ending_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
